source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK', '0.18.0'
    pod 'WXDevtool', '0.9.5'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex', '0.0.1'
    
    pod 'BindingX', :path=>'../../../'
end

target 'WeexDemo' do
    common
end

