source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#inhibit_all_warnings!

target 'BindingDemoRN' do
  pod 'Binding', :path => '../binding-react-native.podspec'

  pod 'React', :path => '/Users/duixiang/alibaba/rn/rntest/node_modules/react-native/React.podspec', :subspecs => [
  'Core',
  'RCTText',
  'RCTNetwork’,
  'RCTWebSocket',
  'CxxBridge',
  ]
  
  pod 'yoga', :path => '/Users/duixiang/alibaba/rn/rntest/node_modules/react-native/ReactCommon/yoga'
  
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '/Users/duixiang/alibaba/rn/rntest/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '/Users/duixiang/alibaba/rn/rntest/node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '/Users/duixiang/alibaba/rn/rntest/node_modules/react-native/third-party-podspecs/Folly.podspec'

end
